### ISSUE TITLE
Use useFieldArray to get an array of objects

### ISSUE THREAD

**Issue by tuddev** [Mini-ghost/vorms#46]
### Discussed in https://github.com/Mini-ghost/vorms/discussions/45

<div type='discussions-op-text'>

<sup>Originally posted by **tuddev** October 12, 2023</sup>
Hello! Can you tell what is the best way to use useFieldArray to get an array of objects from form?</div>

**Comment by Mini-ghost** [comment]
There is already a reply to this question in the discussion, so close this issue.
